### ISSUE TITLE
whats the solution to this

### ISSUE THREAD

**Issue by chirutheboss** [weebzone/Surf-TG#4]
2024-05-08T09:52:29.483479+00:00 app[web.1]: Traceback (most recent call last):
2024-05-08T09:52:29.483481+00:00 app[web.1]: File "<frozen runpy>", line 198, in _run_module_as_main
2024-05-08T09:52:29.483492+00:00 app[web.1]: File "<frozen runpy>", line 88, in _run_code
2024-05-08T09:52:29.483492+00:00 app[web.1]: File "/app/bot/__main__.py", line 54, in <module>
2024-05-08T09:52:29.483633+00:00 app[web.1]: loop.run_until_complete(stop_clients())
2024-05-08T09:52:29.483662+00:00 app[web.1]: File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-05-08T09:52:29.483750+00:00 app[web.1]: File "/app/bot/__main__.py", line 44, in stop_clients
2024-05-08T09:52:29.483816+00:00 app[web.1]: await gather(StreamBot.stop(), UserBot.stop())
2024-05-08T09:52:29.483842+00:00 app[web.1]: File "/usr/local/lib/python3.12/site-packages/pyrogram/methods/utilities/stop.py", line 66, in stop
2024-05-08T09:52:29.483981+00:00 app[web.1]: await do_it()
2024-05-08T09:52:29.483990+00:00 app[web.1]: File "/usr/local/lib/python3.12/site-packages/pyrogram/methods/utilities/stop.py", line 62, in do_it
2024-05-08T09:52:29.484068+00:00 app[web.1]: await self.terminate()
2024-05-08T09:52:29.484071+00:00 app[web.1]: File "/usr/local/lib/python3.12/site-packages/pyrogram/methods/auth/terminate.py", line 41, in terminate
2024-05-08T09:52:29.484138+00:00 app[web.1]: raise ConnectionError("Client is already terminated")
2024-05-08T09:52:29.484159+00:00 app[web.1]: ConnectionError: Client is already terminated
2024-05-08T09:52:29.652024+00:00 heroku[web.1]: Process exited with status 1
2024-05-08T09:52:29.675975+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by weebzone** [comment]
add new session string
