### ISSUE TITLE
help!!!!!

### ISSUE THREAD

**Issue by ak-47-brar** [weebzone/Surf-TG#6]
2024-05-08T12:11:18.691055+00:00 app[web.1]: [08-May-24 12:11:18 PM] [WARNING] - Python-dotenv could not parse statement starting at line 1118
2024-05-08T12:11:18.691120+00:00 app[web.1]: [08-May-24 12:11:18 PM] [WARNING] - Python-dotenv could not parse statement starting at line 1119
2024-05-08T12:11:18.691188+00:00 app[web.1]: [08-May-24 12:11:18 PM] [WARNING] - Python-dotenv could not parse statement starting at line 1120
2024-05-08T12:11:18.691271+00:00 app[web.1]: [08-May-24 12:11:18 PM] [WARNING] - Python-dotenv could not parse statement starting at line 1122
2024-05-08T12:11:18.691335+00:00 app[web.1]: [08-May-24 12:11:18 PM] [WARNING] - Python-dotenv could not parse statement starting at line 1123
2024-05-08T12:11:18.691494+00:00 app[web.1]: [08-May-24 12:11:18 PM] [WARNING] - Python-dotenv could not parse statement starting at line 1133
2024-05-08T12:11:18.691560+00:00 app[web.1]: [08-May-24 12:11:18 PM] [WARNING] - Python-dotenv could not parse statement starting at line 1135
2024-05-08T12:11:18.691844+00:00 app[web.1]: Traceback (most recent call last):
2024-05-08T12:11:18.691854+00:00 app[web.1]:   File "<frozen runpy>", line 198, in _run_module_as_main
2024-05-08T12:11:18.691855+00:00 app[web.1]:   File "<frozen runpy>", line 88, in _run_code
2024-05-08T12:11:18.691864+00:00 app[web.1]:   File "/app/bot/__main__.py", line 8, in <module>
2024-05-08T12:11:18.691998+00:00 app[web.1]:     from bot.config import Telegram
2024-05-08T12:11:18.691998+00:00 app[web.1]:   File "/app/bot/config.py", line 6, in <module>
2024-05-08T12:11:18.692026+00:00 app[web.1]:     class Telegram:
2024-05-08T12:11:18.692027+00:00 app[web.1]:   File "/app/bot/config.py", line 7, in Telegram
2024-05-08T12:11:18.692065+00:00 app[web.1]:     API_ID = int(getenv("API_ID"))
2024-05-08T12:11:18.692095+00:00 app[web.1]:              ^^^^^^^^^^^^^^^^^^^^^
2024-05-08T12:11:18.692104+00:00 app[web.1]: TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-05-08T12:11:18.841422+00:00 heroku[web.1]: Process exited with status 1
2024-05-08T12:11:18.861689+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by weebzone** [comment]
properly fill the config.env
