### ISSUE TITLE
getting this error again and again even after  trying  with different string sessions

### ISSUE THREAD

**Issue by chirutheboss** [weebzone/Surf-TG#9]
Traceback (most recent call last):
2024-05-09T12:15:42.251734+00:00 app[web.1]: File "<frozen runpy>", line 198, in _run_module_as_main
2024-05-09T12:15:42.251742+00:00 app[web.1]: File "<frozen runpy>", line 88, in _run_code
2024-05-09T12:15:42.251743+00:00 app[web.1]: File "/app/bot/__main__.py", line 54, in <module>
2024-05-09T12:15:42.251876+00:00 app[web.1]: loop.run_until_complete(stop_clients())
2024-05-09T12:15:42.251903+00:00 app[web.1]: File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-05-09T12:15:42.252001+00:00 app[web.1]: File "/app/bot/__main__.py", line 44, in stop_clients
2024-05-09T12:15:42.252061+00:00 app[web.1]: await gather(StreamBot.stop(), UserBot.stop())
2024-05-09T12:15:42.252087+00:00 app[web.1]: File "/usr/local/lib/python3.12/site-packages/pyrogram/methods/utilities/stop.py", line 66, in stop
2024-05-09T12:15:42.252246+00:00 app[web.1]: await do_it()
2024-05-09T12:15:42.252250+00:00 app[web.1]: File "/usr/local/lib/python3.12/site-packages/pyrogram/methods/utilities/stop.py", line 62, in do_it
2024-05-09T12:15:42.252320+00:00 app[web.1]: await self.terminate()
2024-05-09T12:15:42.252341+00:00 app[web.1]: File "/usr/local/lib/python3.12/site-packages/pyrogram/methods/auth/terminate.py", line 41, in terminate
2024-05-09T12:15:42.252458+00:00 app[web.1]: raise ConnectionError("Client is already terminated")
2024-05-09T12:15:42.252484+00:00 app[web.1]: ConnectionError: Client is already terminated
2024-05-09T12:15:42.488970+00:00 heroku[web.1]: Process exited with status 1
2024-05-09T12:15:42.511876+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by weebzone** [comment]
fixed now
